PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
INSERT OR IGNORE INTO meta VALUES('schema_version','2');
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('admin','direccion','secretaria','alimentacion','contabilidad','consulta')),salt BLOB NOT NULL,password_hash BLOB NOT NULL,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),failures INTEGER NOT NULL DEFAULT 0,locked_until REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS years(id INTEGER PRIMARY KEY,label TEXT UNIQUE NOT NULL,start_date TEXT NOT NULL,end_date TEXT NOT NULL,institution TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'abierto' CHECK(status IN('abierto','congelado','archivado')),CHECK(start_date<end_date));
CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS records(id INTEGER PRIMARY KEY,year_id INTEGER NOT NULL REFERENCES years(id),kind TEXT NOT NULL,data TEXT NOT NULL CHECK(json_valid(data)),created_at TEXT NOT NULL,updated_at TEXT NOT NULL,version INTEGER NOT NULL DEFAULT 1,UNIQUE(id,year_id));
CREATE INDEX IF NOT EXISTS records_year_kind ON records(year_id,kind);
CREATE UNIQUE INDEX IF NOT EXISTS student_code ON records(year_id,json_extract(data,'$.codigo')) WHERE kind='students';
CREATE UNIQUE INDEX IF NOT EXISTS staff_code ON records(year_id,json_extract(data,'$.codigo')) WHERE kind='staff';
CREATE UNIQUE INDEX IF NOT EXISTS staff_clock_id ON records(year_id,json_extract(data,'$.reloj_id')) WHERE kind='staff' AND json_extract(data,'$.reloj_id')<>'';
CREATE UNIQUE INDEX IF NOT EXISTS attendance_unique ON records(year_id,json_extract(data,'$.personal'),json_extract(data,'$.fecha')) WHERE kind='attendance';
CREATE TABLE IF NOT EXISTS attachments(id INTEGER PRIMARY KEY,record_id INTEGER NOT NULL,year_id INTEGER NOT NULL,name TEXT NOT NULL,mime TEXT NOT NULL,sha256 TEXT NOT NULL,content BLOB NOT NULL,FOREIGN KEY(record_id,year_id) REFERENCES records(id,year_id));
CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,at TEXT NOT NULL,user_id INTEGER REFERENCES users(id),action TEXT NOT NULL,year_id INTEGER REFERENCES years(id),detail TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS academic_levels(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)));
CREATE TABLE IF NOT EXISTS grades(id INTEGER PRIMARY KEY,level_id INTEGER NOT NULL REFERENCES academic_levels(id),name TEXT NOT NULL,min_age INTEGER,max_age INTEGER,sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),UNIQUE(level_id,name),CHECK(min_age IS NULL OR min_age BETWEEN 0 AND 30),CHECK(max_age IS NULL OR max_age BETWEEN 0 AND 30),CHECK(min_age IS NULL OR max_age IS NULL OR min_age<=max_age));
CREATE TABLE IF NOT EXISTS sections(id INTEGER PRIMARY KEY,year_id INTEGER NOT NULL REFERENCES years(id),grade_id INTEGER NOT NULL REFERENCES grades(id),name TEXT NOT NULL,capacity INTEGER,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),UNIQUE(year_id,grade_id,name),CHECK(capacity IS NULL OR capacity BETWEEN 1 AND 200));
CREATE TABLE IF NOT EXISTS session_tokens(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id),token_hash BLOB UNIQUE NOT NULL,created_at TEXT NOT NULL,last_used TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS recovery_keys(user_id INTEGER PRIMARY KEY REFERENCES users(id),salt BLOB NOT NULL,key_hash BLOB NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS food_services(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE COLLATE NOCASE,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS sections_year_grade ON sections(year_id,grade_id);
CREATE TRIGGER IF NOT EXISTS records_insert_lock BEFORE INSERT ON records WHEN (SELECT status FROM years WHERE id=NEW.year_id)<>'abierto' BEGIN SELECT RAISE(ABORT,'El año no está abierto'); END;
CREATE TRIGGER IF NOT EXISTS records_update_lock BEFORE UPDATE ON records WHEN (SELECT status FROM years WHERE id=OLD.year_id)<>'abierto' OR (SELECT status FROM years WHERE id=NEW.year_id)<>'abierto' BEGIN SELECT RAISE(ABORT,'El año no está abierto'); END;
CREATE TRIGGER IF NOT EXISTS records_identity BEFORE UPDATE ON records WHEN OLD.year_id<>NEW.year_id OR OLD.kind<>NEW.kind BEGIN SELECT RAISE(ABORT,'No se puede cambiar el año o tipo'); END;
CREATE TRIGGER IF NOT EXISTS records_delete_lock BEFORE DELETE ON records BEGIN SELECT RAISE(ABORT,'Use estado inactivo o anulado para conservar el historial'); END;
CREATE TRIGGER IF NOT EXISTS attachments_insert_lock BEFORE INSERT ON attachments WHEN (SELECT status FROM years WHERE id=NEW.year_id)<>'abierto' BEGIN SELECT RAISE(ABORT,'El año no está abierto'); END;
CREATE TRIGGER IF NOT EXISTS attachments_update_lock BEFORE UPDATE ON attachments BEGIN SELECT RAISE(ABORT,'Los adjuntos son inmutables'); END;
CREATE TRIGGER IF NOT EXISTS attachments_delete_lock BEFORE DELETE ON attachments BEGIN SELECT RAISE(ABORT,'Los adjuntos son inmutables'); END;
CREATE TRIGGER IF NOT EXISTS audit_update_lock BEFORE UPDATE ON audit BEGIN SELECT RAISE(ABORT,'Auditoría inmutable'); END;
CREATE TRIGGER IF NOT EXISTS audit_delete_lock BEFORE DELETE ON audit BEGIN SELECT RAISE(ABORT,'Auditoría inmutable'); END;
