// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afkieiblgauopgtuzqdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFma2llaWJsZ2F1b3BndHV6cWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDk3NjEsImV4cCI6MjA2NzQ4NTc2MX0.U9TAc_zsxmczoNovvrWIV-EqQcf-VPcvVAYKe9G9_Ow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});